-- ===========================================================================
-- AUTO METRICS SYNC — pg_cron + pg_net
-- ===========================================================================
-- This migration sets up automatic background metrics syncing every 30 minutes.
--
-- SETUP:
--   1. Enable pg_cron:  CREATE EXTENSION IF NOT EXISTS pg_cron;
--   2. Enable pg_net:   CREATE EXTENSION IF NOT EXISTS pg_net;
--   3. Run this entire migration.
--   4. After deploying, insert your secrets into app_settings:
--
--      INSERT INTO app_settings (key, value)
--      VALUES ('cron_secret', 'YOUR_CRON_SECRET'), ('base_url', 'https://cliptwo.vercel.app')
--      ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
--
--      Use the SAME CRON_SECRET value as your Vercel env var.
--      These settings are stored in a database table (not ALTER DATABASE)
--      so they work within Supabase's permission model.
-- ===========================================================================

-- 1. Enable required extensions
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- 2. App settings table (replaces ALTER DATABASE ... SET which requires superuser)
--    Stores key-value pairs for server-side configuration.
--    RLS is disabled — only service_role reads these via pg_cron (no browser access).
CREATE TABLE IF NOT EXISTS public.app_settings (
  key   text PRIMARY KEY,
  value text NOT NULL
);

-- Seed with default values (override after deployment via SQL)
INSERT INTO public.app_settings (key, value) VALUES
  ('cron_secret', ''),
  ('base_url', 'https://cliptwo.vercel.app')
ON CONFLICT (key) DO NOTHING;

-- Grant read to service_role (pg_cron runs with service_role privileges)
GRANT SELECT ON public.app_settings TO service_role;

-- 3. Remove old job if it exists (from previous broken migration)
SELECT cron.unschedule('auto-metrics-sync');

-- 4. Schedule automatic metrics sync every 30 minutes
--    Uses net.http_post() to call the Vercel API endpoint.
--    Reads cron_secret and base_url from app_settings table at runtime.
SELECT cron.schedule(
  'auto-metrics-sync',           -- unique job name
  '*/30 * * * *',                -- every 30 minutes
  $$
    SELECT net.http_post(
      url    := (SELECT value FROM public.app_settings WHERE key = 'base_url') || '/api/metrics/sync/cron',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || (SELECT value FROM public.app_settings WHERE key = 'cron_secret')
      ),
      body := '{}'::jsonb
    );
  $$
);

-- 5. Verify the job is scheduled (optional — for manual inspection)
-- SELECT * FROM cron.job WHERE jobname = 'auto-metrics-sync';
-- SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 5;

-- ===========================================================================
-- SYNC LOCK (database-backed lease — works across separate DB connections)
-- ===========================================================================
-- Supabase/PostgREST uses connection pooling: each HTTP request may use a
-- different database session. Session-level advisory locks are unreliable
-- across requests. This table-based lock is persistent and concurrency-safe.
--
-- The lock row stores: who holds it (owner_id), when it was acquired,
-- and when it expires. If a process crashes, the lease expires and the
-- lock is automatically released.

CREATE TABLE IF NOT EXISTS public.sync_locks (
  lock_key    text PRIMARY KEY,
  owner_id    uuid NOT NULL,
  acquired_at timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz NOT NULL
);

-- Grant full access to service_role (both endpoints use service_role client)
GRANT ALL ON public.sync_locks TO service_role;

-- Acquire a lease lock. Returns true if acquired, false if already held.
-- p_lock_key: identifier for the lock (e.g. 'metrics_sync')
-- p_owner_id: unique ID for this sync run (UUID generated by the caller)
-- p_ttl_seconds: lease duration in seconds (default 10 minutes)
CREATE OR REPLACE FUNCTION public.acquire_sync_lock(
  p_lock_key text,
  p_owner_id uuid,
  p_ttl_seconds integer DEFAULT 600
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Step 1: Delete any expired lock for this key (auto-release on lease expiry)
  DELETE FROM public.sync_locks
  WHERE lock_key = p_lock_key AND expires_at <= now();

  -- Step 2: Try to insert a new lock row.
  -- If another process holds an active (non-expired) lock, the INSERT
  -- will conflict on the PRIMARY KEY and raise unique_violation.
  BEGIN
    INSERT INTO public.sync_locks (lock_key, owner_id, acquired_at, expires_at)
    VALUES (p_lock_key, p_owner_id, now(), now() + make_interval(secs => p_ttl_seconds));
    RETURN true;
  EXCEPTION WHEN unique_violation THEN
    -- Another process holds this lock
    RETURN false;
  END;
END;
$$;

-- Release a lock. Only the owner can release it (prevents accidental release).
CREATE OR REPLACE FUNCTION public.release_sync_lock(
  p_lock_key text,
  p_owner_id uuid
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.sync_locks
  WHERE lock_key = p_lock_key AND owner_id = p_owner_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.acquire_sync_lock(text, uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_sync_lock(text, uuid) TO service_role;

-- Renew a lease lock (heartbeat). Extends expires_at while the lock is still held.
-- Returns true if renewed (we still own it), false if not (expired or taken by another).
-- Called periodically during long-running syncs to prevent lease expiry.
CREATE OR REPLACE FUNCTION public.renew_sync_lock(
  p_lock_key text,
  p_owner_id uuid,
  p_ttl_seconds integer DEFAULT 600
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_updated integer;
BEGIN
  UPDATE public.sync_locks
  SET expires_at = now() + make_interval(secs => p_ttl_seconds)
  WHERE lock_key = p_lock_key
    AND owner_id = p_owner_id
    AND expires_at > now();

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION public.renew_sync_lock(text, uuid, integer) TO service_role;

-- ===========================================================================
-- AFTER DEPLOYMENT — Run these to configure your secrets
-- ===========================================================================
-- Replace '<YOUR_CRON_SECRET>' with the same value as your Vercel CRON_SECRET env var.
--
--   INSERT INTO app_settings (key, value)
--   VALUES ('cron_secret', '<YOUR_CRON_SECRET>'), ('base_url', 'https://cliptwo.vercel.app')
--   ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
--
-- Verify configuration:
--   SELECT * FROM app_settings;
--   SELECT jobid, jobname, schedule FROM cron.job WHERE jobname = 'auto-metrics-sync';
--
-- Check recent runs (after waiting ~30 minutes):
--   SELECT * FROM cron.job_run_details
--   WHERE jobid = (SELECT jobid FROM cron.job WHERE jobname = 'auto-metrics-sync')
--   ORDER BY start_time DESC LIMIT 5;
--
-- Manually test the endpoint:
--   curl -X POST https://cliptwo.vercel.app/api/metrics/sync/cron \
--     -H "Authorization: Bearer <CRON_SECRET>"
