-- =============================================================
-- ⚠️  OBSOLETE — DO NOT RUN ON PRODUCTION DATABASES  ⚠️
-- =============================================================
-- This file was the ORIGINAL storage setup with a PUBLIC bucket.
-- It has been SUPERSEDED by campaign-assets-security.sql which:
--   1. Sets campaign-assets bucket to PRIVATE (public = false)
--   2. Adds path-based public/private access control
--   3. Adds role-based access (creator/admin/clipper)
--   4. Drops all policies from this file and recreates them
--
-- If you run this file AFTER campaign-assets-security.sql, it will
-- REVERT the bucket to public and REPLACE the secure policies.
--
-- AUTHORITATIVE FILE: supabase/campaign-assets-security.sql
--
-- This file is retained for HISTORICAL REFERENCE ONLY.
-- All SQL below is commented out to prevent accidental execution.
-- =============================================================

-- [HISTORICAL — commented out]
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('campaign-assets', 'campaign-assets', true)
-- ON CONFLICT (id) DO NOTHING;

-- [HISTORICAL — commented out — public SELECT policy (replaced by private access control)]
-- DROP POLICY IF EXISTS "campaign_assets_select" ON storage.objects;
-- CREATE POLICY "campaign_assets_select" ON storage.objects
--   FOR SELECT TO public
--   USING (bucket_id = 'campaign-assets');

-- [HISTORICAL — commented out — INSERT policy (replaced by role-based access)]
-- DROP POLICY IF EXISTS "campaign_assets_insert" ON storage.objects;
-- CREATE POLICY "campaign_assets_insert" ON storage.objects
--   FOR INSERT TO authenticated
--   WITH CHECK (
--     bucket_id = 'campaign-assets'
--     AND (storage.foldername(name))[1] = auth.uid()::text
--     AND (storage.foldername(name))[2] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
--     AND EXISTS (
--       SELECT 1 FROM public.campaigns
--       WHERE id = (storage.foldername(name))[2]::uuid
--         AND created_by = auth.uid()
--     )
--   );

-- [HISTORICAL — commented out — DELETE policy (replaced by role-based access)]
-- DROP POLICY IF EXISTS "campaign_assets_delete" ON storage.objects;
-- CREATE POLICY "campaign_assets_delete" ON storage.objects
--   FOR DELETE TO authenticated
--   USING (
--     bucket_id = 'campaign-assets'
--     AND (storage.foldername(name))[1] = auth.uid()::text
--     AND (storage.foldername(name))[2] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
--     AND EXISTS (
--       SELECT 1 FROM public.campaigns
--       WHERE id = (storage.foldername(name))[2]::uuid
--         AND created_by = auth.uid()
--     )
--   );
